# Generated by Django 5.1.4 on 2024-12-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mac', 'Mac'), ('iPad', 'iPad'), ('iPhone', 'iPhone'), ('Watch', 'Watch'), ('Music', 'Music'), ('TV & Home', 'TV & Home'), ('Accessories', 'Accessories'), ('Services', 'Services'), ('Offers', 'Offers')], default='Mac', max_length=50),
        ),
    ]
